# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298a778468501811eee6731de607d2b1d35c240ccd56cb0d09b89a0ad171dde5f73657b37f1330f0e204061e93c99cf1e7fb68c8072ed6da7cf10d30266fa5fa

test:
  secret_key_base: 8989d0a7dc8eba6ca13ae7f3922a6e14ca07f610f77aecdb49958d564f054e37221b5366c585052fe4553b22160e55a7a747e6ab6a8d58eb9f4195c1fe25b437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
